list1=['ram','lakshman','seeta','hanuman']
print(list1)
list1.append("bharat")
print(list1)
print(type(list1[3]))
print(list1[2])
print(list1)
list1.remove("bharat")
print(list1)
list2=["krishna","rukmini","arjun","dharmraj","bheem","nakul","sahadev"]
list1.extend(list2)
print(list1)
